from __future__ import annotations

import hashlib
import re
from typing import Protocol


class RenderableRoute(Protocol):
    domain: str
    target_scheme: str
    target_host: str
    target_port: int
    tls_insecure_skip_verify: bool
    enabled: bool


SAFE_TOKEN_RE = re.compile(r"^[A-Za-z0-9._-]+$")
SAFE_DOMAIN_RE = re.compile(r"^[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)+$")


def render_routes_caddyfile(routes: list[RenderableRoute]) -> str:
    enabled_routes = sorted((route for route in routes if route.enabled), key=lambda route: route.domain)
    lines = [
        "# Generated by Edge Controller. Do not edit manually.",
        "",
    ]

    for route in enabled_routes:
        _validate_route_for_render(route)
        lines.extend(_render_route(route))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def config_checksum(config: str) -> str:
    return hashlib.sha256(config.encode("utf-8")).hexdigest()


def _render_route(route: RenderableRoute) -> list[str]:
    upstream = f"{route.target_host}:{route.target_port}"
    if route.target_scheme == "https":
        upstream = f"https://{upstream}"

    if route.target_scheme == "https" and route.tls_insecure_skip_verify:
        return [
            f"http://{route.domain} {{",
            f"\treverse_proxy {upstream} {{",
            "\t\ttransport http {",
            "\t\t\ttls_insecure_skip_verify",
            "\t\t}",
            "\t}",
            "}",
        ]

    return [
        f"http://{route.domain} {{",
        f"\treverse_proxy {upstream}",
        "}",
    ]


def _validate_route_for_render(route: RenderableRoute) -> None:
    if not SAFE_DOMAIN_RE.fullmatch(route.domain):
        raise ValueError(f"unsafe domain for Caddyfile rendering: {route.domain!r}")
    if route.target_scheme not in {"http", "https"}:
        raise ValueError(f"unsupported target scheme: {route.target_scheme!r}")
    if not SAFE_TOKEN_RE.fullmatch(route.target_host):
        raise ValueError(f"unsafe target host for Caddyfile rendering: {route.target_host!r}")
    if not 1 <= int(route.target_port) <= 65535:
        raise ValueError(f"invalid target port: {route.target_port!r}")
